//
//  Summaries.swift
//  AMF Schedule
//
//  AI-generated summary models
//

import Foundation

/// Today's schedule summary generated by Gemini
struct TodaySummary: Codable {
    let summary: String
    let eventCount: Int
    let generatedAt: Date
    let expiresAt: Date
    
    /// Character limit for today summary: ~320 chars
    static let characterLimit = 320
    
    /// Check if summary is expired (2 hour expiration)
    var isExpired: Bool {
        Date() > expiresAt
    }
    
    /// Check if summary is stale (older than 2 hours)
    var isStale: Bool {
        Date().timeIntervalSince(generatedAt) > 7200
    }
    
    /// Create with automatic expiration
    init(summary: String, eventCount: Int) {
        self.summary = summary
        self.eventCount = eventCount
        self.generatedAt = Date()
        self.expiresAt = Date().addingTimeInterval(7200) // 2 hours
    }
    
    /// Create with all fields (for decoding)
    init(summary: String, eventCount: Int, generatedAt: Date, expiresAt: Date) {
        self.summary = summary
        self.eventCount = eventCount
        self.generatedAt = generatedAt
        self.expiresAt = expiresAt
    }
}

/// Week ahead summary generated by Gemini
struct WeekSummary: Codable {
    let summaryMedium: String  // ~280 chars for medium widget
    let summaryLarge: String   // ~460 chars for large widget
    let eventCount: Int
    let dayBreakdown: [DaySummary]
    let generatedAt: Date
    let expiresAt: Date
    
    /// Character limits
    static let mediumCharacterLimit = 280
    static let largeCharacterLimit = 460
    
    /// Check if summary is expired
    var isExpired: Bool {
        Date() > expiresAt
    }
    
    /// Check if summary is stale
    var isStale: Bool {
        Date().timeIntervalSince(generatedAt) > 7200
    }
    
    /// Create with automatic expiration
    init(summaryMedium: String, summaryLarge: String, eventCount: Int, dayBreakdown: [DaySummary]) {
        self.summaryMedium = summaryMedium
        self.summaryLarge = summaryLarge
        self.eventCount = eventCount
        self.dayBreakdown = dayBreakdown
        self.generatedAt = Date()
        self.expiresAt = Date().addingTimeInterval(7200)
    }
    
    /// Create with all fields (for decoding)
    init(summaryMedium: String, summaryLarge: String, eventCount: Int, dayBreakdown: [DaySummary], generatedAt: Date, expiresAt: Date) {
        self.summaryMedium = summaryMedium
        self.summaryLarge = summaryLarge
        self.eventCount = eventCount
        self.dayBreakdown = dayBreakdown
        self.generatedAt = generatedAt
        self.expiresAt = expiresAt
    }
}

/// Summary for a single day within the week
struct DaySummary: Codable {
    let date: Date
    let dayName: String
    let eventCount: Int
    let highlight: String? // Most notable event/theme
    
    /// Formatted date (e.g., "Tue 02 Dec")
    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "EEE dd MMM"
        return formatter.string(from: date)
    }
    
    /// Short day name (e.g., "Tue")
    var shortDayName: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "EEE"
        return formatter.string(from: date)
    }
}

/// Placeholder summaries for loading states
extension TodaySummary {
    static var placeholder: TodaySummary {
        TodaySummary(
            summary: "Loading today's schedule...",
            eventCount: 0
        )
    }
    
    static var empty: TodaySummary {
        TodaySummary(
            summary: "Clear day ahead. No scheduled events.",
            eventCount: 0
        )
    }
    
    static var error: TodaySummary {
        TodaySummary(
            summary: "Unable to load schedule. Pull to refresh.",
            eventCount: 0
        )
    }
}

extension WeekSummary {
    static var placeholder: WeekSummary {
        WeekSummary(
            summaryMedium: "Loading week ahead...",
            summaryLarge: "Loading week ahead...",
            eventCount: 0,
            dayBreakdown: []
        )
    }
    
    static var empty: WeekSummary {
        WeekSummary(
            summaryMedium: "Open week. No scheduled events.",
            summaryLarge: "Open week. No scheduled events across any calendars.",
            eventCount: 0,
            dayBreakdown: []
        )
    }
    
    static var error: WeekSummary {
        WeekSummary(
            summaryMedium: "Unable to load schedule.",
            summaryLarge: "Unable to load schedule. Open app to refresh.",
            eventCount: 0,
            dayBreakdown: []
        )
    }
}

